import { PrismaPg } from "@prisma/adapter-pg"
// PrismaClient will be generated by `prisma generate` after DB setup

// Global singleton so we don't exhaust connection pool in hot-reload dev environments.
// eslint-disable-next-line @typescript-eslint/no-explicit-any
const globalForPrisma = globalThis as unknown as { prisma: any }

// eslint-disable-next-line @typescript-eslint/no-explicit-any
function createPrismaClient(): any {
  const connectionString = process.env.DATABASE_URL
  if (!connectionString) {
    // Return a bare client without an adapter when DATABASE_URL is not set
    // (e.g. during `next build` before env vars are injected). Queries will
    // fail at runtime until the variable is set in Vercel.
    const { PrismaClient } = require("@prisma/client")
    return new PrismaClient()
  }
  const { PrismaClient } = require("@prisma/client")
  const adapter = new PrismaPg({ connectionString })
  return new PrismaClient({ adapter })
}

export const prisma = globalForPrisma.prisma ?? createPrismaClient()

if (process.env.NODE_ENV !== "production") {
  globalForPrisma.prisma = prisma
}
